import { Tour } from './types';

// Actual tour data for Mr & Mrs Egypt
// costPaid = costPrice - costRemaining
// retailPaid = retailPrice - retailRemaining
export const SEED_TOURS: Omit<Tour, 'id'>[] = [
    {
        tourName: 'Egypt Tour',
        date: '2026-02-26',
        endDate: '2026-03-13',
        customerName: 'Kevin Allison',
        costPrice: 6300,
        retailPrice: 6900,
        costPaid: 6300,
        retailPaid: 6900,
        status: 'upcoming',
        notes: '',
    },
    {
        tourName: 'Egypt Tour',
        date: '2026-04-09',
        endDate: '2026-04-14',
        customerName: 'Dinos Tornivoukas',
        costPrice: 3500,
        retailPrice: 4300,
        costPaid: 1505,
        retailPaid: 1505,
        status: 'upcoming',
        notes: '',
    },
    {
        tourName: 'Egypt Tour',
        date: '2026-04-13',
        endDate: '2026-04-21',
        customerName: 'Andy Yee',
        costPrice: 17870,
        retailPrice: 19295,
        costPaid: 4470,
        retailPaid: 9014.25,
        status: 'upcoming',
        notes: 'Egypt leg',
    },
    {
        tourName: 'Jordan Tour',
        date: '2026-04-21',
        endDate: '2026-04-26',
        customerName: 'Andy Yee',
        costPrice: 8800,
        retailPrice: 10460,
        costPaid: 0,
        retailPaid: 10460,
        status: 'upcoming',
        notes: 'Jordan leg',
    },
    {
        tourName: 'Egypt Tour',
        date: '2026-04-20',
        endDate: '2026-04-26',
        customerName: 'Rachel Shenker',
        costPrice: 6900,
        retailPrice: 9130,
        costPaid: 0,
        retailPaid: 9130,
        status: 'upcoming',
        notes: '',
    },
    {
        tourName: 'Egypt Tour',
        date: '2026-05-21',
        endDate: '2026-06-02',
        customerName: 'Stephanie Sargent',
        costPrice: 3740,
        retailPrice: 4350,
        costPaid: 3740,
        retailPaid: 4350,
        status: 'upcoming',
        notes: '',
    },
    {
        tourName: 'Egypt Tour',
        date: '2027-12-20',
        endDate: '2028-01-02',
        customerName: 'Julie Liddy',
        costPrice: 31000,
        retailPrice: 39800,
        costPaid: 7750,
        retailPaid: 19900,
        status: 'upcoming',
        notes: '',
    },
];
